/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.modules.wiki.extractor.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the WikiContent service. Represents a row in the &quot;WikiExtractor_WikiContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.modules.wiki.extractor.model.impl.WikiContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.modules.wiki.extractor.model.impl.WikiContentImpl}.
 * </p>
 *
 * @author Vilmos Papp
 * @see WikiContent
 * @see com.liferay.modules.wiki.extractor.model.impl.WikiContentImpl
 * @see com.liferay.modules.wiki.extractor.model.impl.WikiContentModelImpl
 * @generated
 */
@ProviderType
public interface WikiContentModel extends BaseModel<WikiContent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wiki content model instance should use the {@link WikiContent} interface instead.
	 */

	/**
	 * Returns the primary key of this wiki content.
	 *
	 * @return the primary key of this wiki content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wiki content.
	 *
	 * @param primaryKey the primary key of this wiki content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wiki ID of this wiki content.
	 *
	 * @return the wiki ID of this wiki content
	 */
	public long getWikiId();

	/**
	 * Sets the wiki ID of this wiki content.
	 *
	 * @param wikiId the wiki ID of this wiki content
	 */
	public void setWikiId(long wikiId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WikiContent wikiContent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WikiContent> toCacheModel();

	@Override
	public WikiContent toEscapedModel();

	@Override
	public WikiContent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}