/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.modules.wiki.extractor.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.modules.wiki.extractor.model.WikiContent;
import com.liferay.modules.wiki.extractor.model.WikiContentModel;
import com.liferay.modules.wiki.extractor.model.WikiContentSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the WikiContent service. Represents a row in the &quot;WikiExtractor_WikiContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link WikiContentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WikiContentImpl}.
 * </p>
 *
 * @author Vilmos Papp
 * @see WikiContentImpl
 * @see WikiContent
 * @see WikiContentModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class WikiContentModelImpl extends BaseModelImpl<WikiContent>
	implements WikiContentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wiki content model instance should use the {@link WikiContent} interface instead.
	 */
	public static final String TABLE_NAME = "WikiExtractor_WikiContent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "wikiId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("wikiId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table WikiExtractor_WikiContent (wikiId LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table WikiExtractor_WikiContent";
	public static final String ORDER_BY_JPQL = " ORDER BY wikiContent.wikiId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY WikiExtractor_WikiContent.wikiId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.modules.wiki.extractor.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.modules.wiki.extractor.model.WikiContent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.modules.wiki.extractor.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.modules.wiki.extractor.model.WikiContent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static WikiContent toModel(WikiContentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		WikiContent model = new WikiContentImpl();

		model.setWikiId(soapModel.getWikiId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<WikiContent> toModels(WikiContentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<WikiContent> models = new ArrayList<WikiContent>(soapModels.length);

		for (WikiContentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.modules.wiki.extractor.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.modules.wiki.extractor.model.WikiContent"));

	public WikiContentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _wikiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWikiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _wikiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WikiContent.class;
	}

	@Override
	public String getModelClassName() {
		return WikiContent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("wikiId", getWikiId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long wikiId = (Long)attributes.get("wikiId");

		if (wikiId != null) {
			setWikiId(wikiId);
		}
	}

	@JSON
	@Override
	public long getWikiId() {
		return _wikiId;
	}

	@Override
	public void setWikiId(long wikiId) {
		_wikiId = wikiId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			WikiContent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WikiContent toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (WikiContent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WikiContentImpl wikiContentImpl = new WikiContentImpl();

		wikiContentImpl.setWikiId(getWikiId());

		wikiContentImpl.resetOriginalValues();

		return wikiContentImpl;
	}

	@Override
	public int compareTo(WikiContent wikiContent) {
		long primaryKey = wikiContent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof WikiContent)) {
			return false;
		}

		WikiContent wikiContent = (WikiContent)obj;

		long primaryKey = wikiContent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<WikiContent> toCacheModel() {
		WikiContentCacheModel wikiContentCacheModel = new WikiContentCacheModel();

		wikiContentCacheModel.wikiId = getWikiId();

		return wikiContentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(3);

		sb.append("{wikiId=");
		sb.append(getWikiId());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(7);

		sb.append("<model><model-name>");
		sb.append("com.liferay.modules.wiki.extractor.model.WikiContent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>wikiId</column-name><column-value><![CDATA[");
		sb.append(getWikiId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = WikiContent.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			WikiContent.class
		};
	private long _wikiId;
	private WikiContent _escapedModel;
}